### ISSUE TITLE
Automatic maintenance for Field createdTime and lastUpdatedTime

### ISSUE THREAD

**Issue by lijiaxi2018** [lijiaxi2018/CaptionLive#13]
## Problem
- The currently User controllers requires createdTime and lastUpdatedTime, which is not desirable because those two fields should be automatically maintenanced by the framework.

**Comment by liulin0x3c** [comment]
Using `@JsonIgnore` to ignore fileds `createdTime` and `lastUpdatedTime`. The User code just a demo, I will close this issue and fix it after  the real User code is push. cc @muyangshaog @lijiaxi2018
