### ISSUE TITLE
API should not overwrite existing database when restarting

### ISSUE THREAD

**Issue by lijiaxi2018** [lijiaxi2018/CaptionLive#4]
API currently  removes all existing data in the database and create the same tables again when it is restarted. Ideally the database should be persisted and api should not re-create the same tables.

**Comment by liulin0x3c** [comment]
It will be fixed after merging the PR[ validate rather than create; add dependence to support validate #6 ](https://github.com/lijiaxi2018/CaptionLive/pull/6)

**Comment by lijiaxi2018** [comment]
Resolved by #6
