### ISSUE TITLE
Decide necessary timestamp for database tables

### ISSUE THREAD

**Issue by lijiaxi2018** [lijiaxi2018/CaptionLive#8]
Decide which timestamp types (CreatedTime, LastUpdatedTime) are necessary fields for each table in the database.

**Comment by liulin0x3c** [comment]
it is recommended to include the "lastUpdatedTime" and "createdTime" columns in every table of the database.
ref: PR #9

**Comment by lijiaxi2018** [comment]
Resolved by #9 . Thank you!
